version: "3.8"

services:
  bible-db:
    image: bitnami/postgresql
    container_name: bible-db
    ports:
      - "5432:5432"
    environment:
      POSTGRESQL_DATABASE: bible
      POSTGRESQL_USERNAME: docker
      POSTGRESQL_PASSWORD: docker
    volumes:
      - ./seed:/seed
    restart: unless-stopped
